config/routes.rb
Rails.application.routes.draw do
 get "home/about", to: "homes#about"
 root :to => 'homes#top'
  devise_for :users
  resources :books, only: [:index, :show, :edit, :create, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]
  get "users/:id" => "users#show", as: :mypage
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
belongs_to :user
attachment :profile_image

	validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name,uniqueness: true
  validates :name, presence: true, length: { in: 2..20, }
  validates :introduction, length: { maximum: 50 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         

  has_many :books, dependent: :destroy


attachment :profile_image


 def email_required?
   false
 end
 def email_changed?
   false
 end
end

 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
   root_path
  end
  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email])
  end
end
 

 

app/controllers/books_controller.rb
class BooksController < ApplicationController
 before_action :authenticate_user!
   def new
  	@book = Book.new
  end

  def index
  	@books = Book.all
  	@book = Book.new
  end

  def create
    @books = Book.all
  	@book = Book.new(book_params)
  	@book.user_id = current_user.id
  	if @book.save
  	   flash[:notice] = "You have created book successfully."
  	   redirect_to book_path(@book.id)
  	else
  	  render :index
  	end
  end

  def show
  	@book = Book.find(params[:id])
  	@book_new = Book.new
  	@user = @book.user
  end

  def edit
  	@book = Book.find(params[:id])
  	if @book.user == current_user
  	  render :edit
  	else
  	  redirect_to books_path
  	end
  end


  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  	   flash[:notice] = "You have updated book successfully."
  	   redirect_to book_path
  	else
  	   render :edit
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path
  end

private
  def book_params
  	params.require(:book).permit(:title, :body)
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
  def about
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    
    def index
  	@users = User.all
  	@book = Book.new
    end
    
  def show
    @user = User.find(params[:id])
  	@book = Book.new
  	@books = @user.books.page(params[:page]).reverse_order
  end
  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end
  def update
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/_error.html.erb/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/_error.html.erb/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/books/_error.html.erb
 <% if model.errors.any? %>
      <div class="alert alert-warning">
  	    <h3><%= model.errors.count %>errors prohibited this obj from being saved:</h3>
        <ul>
          <% model.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

app/views/books/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/books/_header.html.erb
<head>
    <title>Bookers</title>
    <meta name="csrf-param" content="authenticity_token" />
  </head>

<header>
  <nav class='navbar navbar-expand-lg navbar-dark bg-dark' >
    <div class="container">
      <a class="navbar-brand" href="/">
        <span>Bookers</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expand="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li>
            <a class="fas fa-home nav-link text-light" href="/users/<%= current_user.id %>"> Home</a>
          </li>
          <li>
            <a class="fas fa-users nav-link text-light" href="/users"> Users</a>
          </li>
          <li>
            <%= link_to "Books", books_path, class: "fas fa-book-open nav-link text-light" %>
          </li>
          <li>
            <%= link_to " logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %>
          </li>
          <% else %>
          <li>
            <a class="fas fa-home nav-link text-light" href="/"> Home</a>
          </li>
          <li>
            <%= link_to " About", home_about_path, class: "fas fa-link nav-link text-light" %>
          </li>
          <li>
            <%= link_to " Sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %>
          </li>
          <li>
            <a class="fas fa-sign-in-alt nav-link text-light" href="/users/sign_in"> login</a>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/books/_left.html.erb
<div class='col-md-3'>
  <h2>User info</h2>
  <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= current_user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= current_user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <a class="btn btn-outline-secondary btn-block fas fa-user-cog edit_user_path" href="/users/<%= current_user.id %>/edit"></a>
  </div>
  <h2 class="mt-3">New book</h2>
  <form action="/books" accept-charset="UTF-8" method="post">
    <%= form_with model:book_new, local:true do |f| %>
    <div class="form-group">
      <div>
        <label for="book_title">Title</label>
      </div>
      <div>
        <%= f.text_field :title, class: "form-control book_title" %>
      </div>
    </div>
    <div class="form-group">
      <div>
        <label for="book_opinion">Opinion</label>
      </div>
      <div>
        <%= f.text_area :body, class: "form-control book_body" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.submit "Create Book", class: "btn btn-success" %>
    </div>
    <% end %>
  </form>
</div>

app/views/books/edit.html.erb
<div class='body'>
 <div class='container'>
  <p id="notice"></p>
  <div class='row'>
	  <div class='col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto'>
	    
   <% if @book.errors.any? %>
    <div class="alert alert-warning">
     <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
     <ul>
     <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
     <% end %>
     </ul>
    </div>
    <% end %>
     
	   <h1>Editing Book</h1>
	    
	    <%= form_for(@book) do |f| %>
  	  <div class="field row">
       <h4>Title</h4>
       <%= f.text_field :title, class:"form-control title" %>
      </div>

      <div class="field row">
       <h4>Opinion</h4>
       <%= f.text_area :body, class:"form-control body" %>
      </div>

      <br>

      <div class="actions row">
       <%= f.submit "Update Book", class: "btn btn-success" %>
      </div>

      
	      <%= link_to "Show", book_path(@book) %> |
	      <%= link_to "Back", books_path %>
	    
      <% end %>
      
   </div>
  </div>
 </div>

app/views/books/index.html.erb
 <body>
<script src="https://kit.fontawesome.com/37dc3c1a90.js" crossorigin="anonymous"></script>

<div class="container px-5 px-sm-0">
  <div class="row">







<div class='col-md-3'>
  <h2>User info</h2>
  <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= current_user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= current_user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <a class="btn btn-outline-secondary btn-block fas fa-user-cog edit_user_path" href="/users/<%= current_user.id %>/edit"></a>
  </div>
  <h2 class="mt-3">New book</h2>
    <%= form_with model:@book, local:true do |f| %>
    <div class="form-group">
      <div>
        <label>Title</label>
      </div>
      <div>
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div>
        <label>Opinion</label>
      </div>
      <div>
        <%= f.text_area :body, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.submit "Create Book", class: "btn btn-success" %>
    </div>
    <% end %>
</div>





    <div class='col-md-8 offset-md-1'>
      
      
      
      

      <h2>Books</h2>
      <table class='table table-hover table-inverse'>
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
        <tr>
          <td><%= link_to user_path(book.user_id) do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg",size:'40x40' %>
          <% end %></td>

        <td>
          <%= link_to book.title, book_path(book) %>
          </td>
          <td>
          <%= book.body %>
          </td>
        </tr>
        <% end %>
      </tbody>
      </table>
    </div>
  </div>
</div>
</body>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<script src="https://kit.fontawesome.com/37dc3c1a90.js" crossorigin="anonymous"></script>

<div class="container">
  <div class="row">


<div class='col-md-3'>
  <h2>User info</h2>
  <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
    
    <a class="btn btn-outline-secondary btn-block fas fa-user-cog edit_user_path" href="/users/<%= @user.id %>/edit"></a>
  </div>
  <h2 class="mt-3">New book</h2>
    <%= form_with model:@book_new, local:true do |f| %>
    <div class="form-group">
      <div>
        <label for="book_title">Title</label>
      </div>
      <div>
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div>
        <label>Opinion</label>
      </div>
      <div>
        <%= f.text_area :body, class: "form-control" %>
      </div>
    </div>
    <div>
      <%= f.submit "Create Book", class: "btn btn-success" %>
    </div>
    <% end %>
</div>



    <div class="col-md-8 offset-md-1">
      
      
      
      



      <h2>Book detail</h2>
      <table class='table'>
        <tbody>
          <tr>
            <td>
              <%= link_to(user_path(@book.user)) do %>
              <% if @book.user == current_user %>
              <%= attachment_image_tag current_user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
              <% else %>
              <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
              <% end %>
              <div>
                <%= @book.user.name %>
                <% end %>
              </div>
            </td>
            <td>
              <%= link_to @book.title, book_path(@book.id) %>
             
            </td>
            <td><%= @book.body %></td>
            <% if @book.user == current_user %>
            <td>
              <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %>
            </td>
            <td>
              <%= link_to "Destroy", book_path(@book.id), class:"btn btn-sm btn-danger", method: :delete, data: {confirm: "本当に削除しますか？"} %>
            </td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<body>
  <div class='body'>


  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>

  <div class='container'>
    <div class="row">
   	  <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
        <h1>welcome to
        <i class="fas fa-book"></i>
          <strong>Bookers</strong>
          !!</h1>
      </div>
    </div>
  </div>

</body>

app/views/homes/top.html.erb
<body>
  <div class='body'>


  <div class='container'>
    <div class="row">
   	  <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
        <h1>welcome to
        <i class="fas fa-book"></i>
          <strong>Bookers</strong>
          !!</h1>
          <p>In
          <i class="fas fa-book"></i>
          <strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about various books!</p>

          <div class="btn-wrapper col-10 mx-auto">
            <div class="row">
              <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
            </div>
            <div class="row">
              <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render 'books/header' %>
    
    <div class= "body">

    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    
    </div>
    
  
    <%= yield %>
    <%= render 'books/footer' %>
  </body>
</html>

app/views/users/_user.html.erb
<h2>User info</h2>
  <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <a class="btn btn-outline-secondary btn-block fas fa-user-cog edit_user_path" href="/users/<%= current_user.id %>/edit"></a>
    </div>

app/views/users/edit.html.erb
<h2>User info</h2>
<%# USER VALIDATION %>
<% if @user.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
  <h2><%= @user.errors.count %> errors prohibited this user from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%#  %>
<%= form_for(@user) do |f| %>
  <div class="field">
    <label for="user_name">Name</label>
    <%= f.text_field :name, autofocus: true, class:"name", placeholder:"name"%>
  </div>
  <div class="field">
    <label for="user_image">Image</label>
    <%= f.attachment_field :profile_image %>
  </div>
  <div class="field">
    <label for="user_introduction">Introduction</label>
    <%= f.text_area :introduction, class:"user_body introduction", id:"user_introduction" %>
  </div>
  <div class="actions">
    <%= f.submit "Update User", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
     
      <h2>New book</h2>
      
    </div>
    <div class="col-xs-9">
  	  <table class="table table-sm user-index">
	  	  <h2>Users</h2>
        <thead>
          <th>image</th>
          <th>name</th>
          <th></th>
  	    </thead>
  	  	<tbody>
  	  	  <% @users.each do |user| %>
	  	  	<tr>
	  	  	  
	  	  	  <td><%= user.name %></td>
	  	  	  <td><%= link_to "Show", "/users/#{user.id}" %></td>
	  	  	</tr>
  	  	  <% end %>
  	  	</tbody>
  	  </table>
  	</div>
  </div>

app/views/users/show.html.erb
<div class="container px-5 px-sm0">
  <div class="row">










<div class='col-md-3'>
  <h2>User info</h2>
  <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <a class="btn btn-outline-secondary btn-block fas fa-user-cog edit_user_path" href="/users/<%= @user.id %>/edit"></a>
  </div>
  <h2 class="mt-3">New book</h2>
    <%= form_with model:@book, local:true do |f| %>
    <div class="form-group">
      <div>
        <label>Title</label>
      </div>
      <div>
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div>
        <label>Opinion</label>
      </div>
      <div>
        <%= f.text_area :body, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.submit "Create Book", class: "btn btn-success" %>
    </div>
    <% end %>
</div>





    <div class="col-md-8 offset-md-1">



      <h2>Books</h2>
      <table class='table tablse-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
        <tr>
          <td><%= link_to(user_path(@user)) do %><%= attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40'  %><% end %></td>
          <td><%= link_to(book_path(book)) do %>
        	  <%= book.title %><% end %></td>
          <td><%= book.body %></td>
          <% if book.user == current_user %>

          <td>
          </td>
          <td>
          </td>
          <% end %>
        </tr>
        <% end %>
        
        </tbody>
       </table>
    </div>
  </div>
</div>